### ISSUE TITLE
Need to handle Null value response

### ISSUE THREAD

**Issue by bjhiltbrand** [auzick/OpenHab.UniFiProxy#4]
This is super promising! Thank you for putting something like this together while Ubiquiti drags their feet to implement the API again in Unifi Protect.

I setup my appsettings.json file and ran the program, but was immediately stopped by this error:

[20:58:25] UniFi authentication succeeded.
Unhandled exception. System.AggregateException: One or more errors occurred. (The JSON value could not be converted to System.Int64. Path: $.lastLoginTime | LineNumber: 0 | BytePositionInLine: 101.)
 ---> System.Text.Json.JsonException: The JSON value could not be converted to System.Int64. Path: $.lastLoginTime | LineNumber: 0 | BytePositionInLine: 101.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
   at System.Text.Json.Utf8JsonReader.TryGetInt64(Int64& value)
   at System.Text.Json.Utf8JsonReader.GetInt64()
   at System.Text.Json.Serialization.Converters.JsonConverterInt64.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.HandleNull(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at OpenHab.UniFiProxy.Extensions.ParseJson[T](String json) in E:\Proj\OpenHabUniFiProxy\Extensions.cs:line 23
   at OpenHab.UniFiProxy.Extensions.ParseResponseJson[T](HttpResponseMessage response) in E:\Proj\OpenHabUniFiProxy\Extensions.cs:line 14
   at OpenHab.UniFiProxy.Clients.UniFiClient.Authenticate() in E:\Proj\OpenHabUniFiProxy\ApiClients\UniFiClient.cs:line 209
   at OpenHab.UniFiProxy.Clients.UniFiClient.CallUniFiApi(HttpRequestMessage request) in E:\Proj\OpenHabUniFiProxy\ApiClients\UniFiClient.cs:line 101
   at OpenHab.UniFiProxy.Clients.UniFiClient.GetBootstrap() in E:\Proj\OpenHabUniFiProxy\ApiClients\UniFiClient.cs:line 44
   at OpenHab.UniFiProxy.Program.Initialize() in E:\Proj\OpenHabUniFiProxy\Program.cs:line 119
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at OpenHab.UniFiProxy.Program.Main(String[] args) in E:\Proj\OpenHabUniFiProxy\Program.cs:line 33
Aborted (core dumped)

It looks like it was able to authenticate, but then received a null value for a "lastLoginTime" variable, that was unable to be parsed to Int64. I may be very wrong on that, but that's what it looks like to me. I tried following the stack trace in code, but I didn't see anywhere where I could add error handling for null values. Admittedly, .Net is not my bread and butter, so I defer to you on this. Any thoughts?

P.S.- I should also note that I am attempting this using the Linux Standalone zip.

**Comment by bjhiltbrand** [comment]
I just tried again using the Windows Standalone zip, with the same exceptions and failure.

**Comment by auzick** [comment]
Apologies for the long delay getting back to you. I've updated a bunch of properties to be nullable ... and one property (hasAec) to allow an object instead of a boolean, since instead of "false" Unifi sometimes returns an empty array, for reasons that surpass understanding. Give the new version a shot and let me know if it works for you.

**Comment by auzick** [comment]
Most properties are now nullable.
